server:
  port: 8001
spring:
  application:
    name: cloud-eureka-provider
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: provider8001   #actuator
    prefer-ip-address: true  #访问路径显示ip
    lease-renewal-interval-in-seconds: 1  #Eureka客户端向服务端发送心跳的间隔时间，单位为秒，默认30秒
    lease-expiration-duration-in-seconds: 2 #Eureka服务端在收到最后一次心跳后等待的时间上限，单位为秒，默认90秒
